# August 21, 2015
# https://docpad.org/docs/deploy

# Use the latest travis infrastructure
sudo: false

# Run travis only on the master branch
branches:
  only:
    - master

# We use node
language: ruby
rvm:
  - "2.2"

# Prepare and run our tests
install: gem install travis --no-rdoc --no-ri
script:  travis login --skip-completion-check --github-token "$GITHUB_TRAVIS_TOKEN" && travis restart --skip-completion-check -r "$TRAVIS_REBUILD_REPO"

# Custom deployment
# travis encrypt "GITHUB_TRAVIS_TOKEN=$GITHUB_TRAVIS_TOKEN" --add env.global
env:
  global:
    - TRAVIS_REBUILD_REPO='docpad/website'
    - secure: WZQTSijC2F4q/P24/KNqIsiyvrjpF9e7RpUYUKx92kq1sWLnTv1nLa1W4+RiD4V93wI8k2qDzSneK8ntXTG8fiHeH0k2XsoKgxWmfZmV7F2bSORHWIvGpHVgeSpkr1HAykH9j7mzn0snMZIW4HsFkC5OBrQ93nVdKKyEuJPRmLQ=
