# August 21, 2015
# https://docpad.org/docs/deploy

# Use the latest travis infrastructure
sudo: false

# Run travis only on the master branch
branches:
  only:
    - master

# We use node
language: ruby
rvm:
  - "2.2"

# Prepare and run our tests
install: gem install travis --no-rdoc --no-ri
script: travis restart --debug --skip-completion-check -r "$TRAVIS_REBUILD_REPO" -t "$TRAVIS_ACCESS_TOKEN"

# Custom deployment
# travis encrypt "TRAVIS_ACCESS_TOKEN=$TRAVIS_ACCESS_TOKEN" --add env.global
env:
  global:
    - TRAVIS_REBUILD_REPO='docpad/website'
    - secure: Tvz/lldT5kIskI6uZkC2jdMj6lQZk90cCUdovH/wu8F2m32C5c8wNR3C70ZqMEwAATFfpyIeYlVJs3WTM1H3OjLyJSROfna4LdIYByNDyXV5O745a+2NoOiPB+ehbf9/W3P1BVazw4S7vTh9cJ4EmdpEtvol7CkBHmNp/fJPbtg=
